// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhxvfcxawoubuqkxrumi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoeHZmY3hhd291YnVxa3hydW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTU0NDEsImV4cCI6MjA2NzA3MTQ0MX0.EfKJsJzSoMpcZpAygG-OrdmpI22vNB3uTucQ45xoFK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});